version: '3.7'
services:


  ci-app-front:
    build:
      context: .
    container_name: ci-angular
    image: ayoubmabrouk1/ci-front:latest
    ports:
      - "8888:80"
    networks:
      - ci-network

  ci-db:
    container_name: ci-db
    image: mysql:8.0
    env_file:
      - .env
    networks:
      - ci-network
    environment:
      - MYSQL_USER=new_user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=TpAchatProjectdb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - dbvol:/var/lib/mysql
    ports:
      - "3306:3307"
    restart: always

  ci-app:
    build:
      context: .
    container_name: ci-spring
    image: ayoubmabrouk1/achat:latest
    env_file:
      - .env
    ports:
      - "8089:8089"
    networks:
      - ci-network
    depends_on:
      - ci-db
    environment:
      - MYSQL_HOST=ci-db
      - MYSQL_USERNAME=new_user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=TpAchatProjectdb
      - MYSQL_PORT=3307


networks:
  ci-network:
    name: ci-network

volumes:
  dbvol: